#!/usr/bin/env python3

import json
import sys


def readjson(filename):
    json_str = open(filename).read()
    j = json.loads(json_str)
    return j


if __name__ == '__main__':
    readjson(sys.argv[1])
