FROM centos:centos7

RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo \
 && yum update -y \ 
 && yum -y install kde-l10n-Chinese \
 && reinstall -y glibc-common \
 && localedef -c -f UTF-8 -i zh_CN zh_CN.utf8 \
 && yum update -y \
 && rm -f /etc/yum.repos.d/epel.repo && rm -f /etc/yum.repos.d/epel-testing.repo \
 && curl -o /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo \
 && yum update -y \ 
 && yum install -y devtoolset-8

RUN yum install -y make wget python3 which git bzip2 glibc-common python3-devel mysql-devel \
 && yum install -y https://cdn.mysql.com/archives/mysql-connector-c++/mysql-connector-c++-1.1.12-linux-el7-x86-64bit.rpm \
 && yum clean all

RUN pip3 --no-cache-dir install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple \
 && pip3 --no-cache-dir install GitPython apio requests scons lxml mako numpy wget sqlparser pandas openpyxl \
    -i https://mirrors.aliyun.com/pypi/simple \
 && mkdir -p /tmp/ccache

# && yum install -y glibc-langpack-en \
CMD ['scl enable devtoolset-8 bash']


ENV CCACHE_DIR=/tmp/ccache \
    CCACHE_SIZE=10G \
    CCACHE_UMASK=0 \
    C_INCLUDE_PATH=/root/usr/include:${C_INCLUDE_PATH} \
    LD_LIBRARY_PATH=/root/usr/lib:/root/usr/lib64:${LD_LIBRARY_PATH} \
    LIBRARY_PATH=/root/usr/lib:/root/usr/lib64:${LIBRARY_PATH} \
    PATH=/root/usr/bin:${PATH} \
    LANG=zh_CN.UTF-8 \
    LANGUAGE=zh_CN:zh \
    LC_ALL=zh_CN.UTF-8
