FROM w505703394/alpine:release_base

COPY boost_install /develop/boost

COPY mysql_install /develop/mysql

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/develop/boost/lib:/develop/mysql/lib \
    LIBRARY_PATH=$LD_LIBRARY_PATH


