FROM centos

RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-8.repo \
 && yum update -y \
 && yum install -y epel-release \
 && yum update -y \
 && yum install -y make mysql-devel wget python3 which ccache git bzip2 glibc-common gcc-c++ gdb \
 && yum clean all \
 && pip3 install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple \
 && pip3 install GitPython apio requests scons lxml mako numpy wget sqlparser pandas openpyxl -i https://pypi.tuna.tsinghua.edu.cn/simple \
 && mkdir -p /tmp/ccache

# && yum install -y make mysql-devel wget python3 which ccache git bzip2 kde-l10n-Chinese reinstall glibc-common gcc-c++ gdb \
# && ccache --max-size=10G >/dev/null \
# && localedef -c -f UTF-8 -i zh_CN zh_CN.utf8

ENV CCACHE_DIR=/tmp/ccache \
    CCACHE_SIZE=10G \
    CCACHE_UMASK=0 \
    C_INCLUDE_PATH=/root/usr/include:${C_INCLUDE_PATH} \
    LD_LIBRARY_PATH=/root/usr/lib:${LD_LIBRARY_PATH} \
    LIBRARY_PATH=/root/usr/lib:${LIBRARY_PATH} \
    PATH=/root/usr/bin:${PATH}

#    LANG=zh_CN.UTF-8 \
#    LANGUAGE=zh_CN:zh \
#    LC_ALL=zh_CN.UTF-8
