FROM centos

RUN  yum update -y \                                  
  && yum install -y gcc-c++ mysql-devel \
  && yum clean all                                    

COPY boost_install /opt/boost

COPY mysql_install /opt/mysql

