FROM registry.cn-shanghai.aliyuncs.com/love996/ubuntu1604:dev_base


RUN sh -c '. /etc/lsb-release && echo "deb http://mirrors.tuna.tsinghua.edu.cn/ros/ubuntu/ xenial main" > /etc/apt/sources.list.d/ros-latest.list' \
 && curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | apt-key add - \
 && apt update \
 && apt install -y ros-kinetic-desktop-full \
 && . /opt/ros/kinetic/setup.bash \
 && apt install -y python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential \
 && rosdep init \
 && rosdep update


CMD [". /opt/ros/kinetic/setup.bash"]
